### ISSUE TITLE
AWTGLCanvas: make PlatformGLCanvas platformCanvas accessible

### ISSUE THREAD

**Issue by hageldave** [LWJGLX/lwjgl3-awt#10]
First of all, great work!

`AWTGLCanvas` has a `private PlatformGLCanvas platformCanvas` which it locks during
render and sets its context. I need to access this `platformCanvas` in order to do the same (locking, setting context) outside rendering in order to `glReadPixels` from a frame buffer object.  If the field was `protected` instead of `private` this would be great. 

Currently I'm resorting to reflection like this:
```java

public abstract class FBOCanvas extends AWTGLCanvas {
...

PlatformGLCanvas platformcanvas=null;
try {
	Field declaredField = AWTGLCanvas.class.getDeclaredField("platformCanvas");
	declaredField.setAccessible(true);
	platformcanvas = (PlatformGLCanvas) declaredField.get(FBOCanvas.this);
	platformcanvas.lock();
	platformcanvas.makeCurrent(FBOCanvas.this.context);
	color[0] = MyGlUtils.fetchPixel(fbo.getFBOid(),GL30.GL_COLOR_ATTACHMENT0, x, y);
} catch (IllegalArgumentException | IllegalAccessException | NoSuchFieldException | SecurityException | AWTException e) {
	e.printStackTrace();
} finally {
	if(Objects.nonNull(platformcanvas)){
		try {
			platformcanvas.makeCurrent(0L);
			platformcanvas.unlock();
		} catch (AWTException e) {
		}
	}
}

...
}

public static int fetchPixel(int fboID, int attachment, int x, int y){
	int pixel = 0;
	GL30.glBindFramebuffer(GL30.GL_READ_FRAMEBUFFER, fboID);
	{
		GL11.glReadBuffer(attachment);
		int[] rgba_bytes = new int[1];
		GL11.glReadPixels(x, y, 1, 1, GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, rgba_bytes);
		pixel = rgba_bytes[0];
	}
	GL30.glBindFramebuffer(GL30.GL_READ_FRAMEBUFFER, 0);
	return pixel;
}
```

**Comment by httpdigest** [comment]
Hey, thanks for the feedback and your user case. I have a different proposition: Would it suit you if we added a `AWTGLCanvas.<T>executeInContext(Callable<T>)` or `AWTGLCanvas.runInContext(Runnable)`. So, without exposing any internals (which I would probably do anyways), we can give the user a method to execute any code in the context of the GL context.

**Comment by httpdigest** [comment]
See: https://github.com/LWJGLX/lwjgl3-awt/commit/d458f55f48049cadf2dd39804a33c660ef4cf81c
0.1.2 will be available on Maven Central in a few minutes.

**Comment by hageldave** [comment]
This is actually a pretty good idea. Thanks for the quick reply.
