### ISSUE TITLE
JAWT_GetDrawingSurface method arguments changed in LWJGL 3.2.2

### ISSUE THREAD

**Issue by eduramiba** [LWJGLX/lwjgl3-awt#11]
Hi,
It seems that LWJGL release 3.2.2 broke `JAWT_GetDrawingSurface` and possibly other functions in this commit https://github.com/LWJGL/lwjgl3/commit/f063c82f33ee12ce59222f9cb98f91aa85685d76#diff-49e1ee727167ebcbe8013814074155a0 making lwjgl3-awt fail.

Thank you

**Comment by httpdigest** [comment]
Thanks for letting us know! @Spasi fixed this with https://github.com/LWJGLX/lwjgl3-awt/commit/aa4398447aaef97c2af8a133aa6eabfd3e6c12f4
