### ISSUE TITLE
AWTGLCanvas being cleared right after rendering

### ISSUE THREAD

**Issue by hageldave** [LWJGLX/lwjgl3-awt#13]
Hi, I'm using the AWTGLCanvas to draw some stuff on demand. I dont want to use a render loop because thats unnecessary and a waste of system resources. For this I override the ```repaint()``` method to call ```render()``` so I can use that whenever repainting is necessary like i would with any other custom swing/awt component. The problem is, that without a render loop as in your [example](https://github.com/LWJGLX/lwjgl3-awt/blob/master/test/org/lwjgl/opengl/awt/AWTTest.java) the rendering is just visible for a very short time (like a flicker) and then the Canvas is just gray again.
I figured out that overriding the Canvas ```paint(Graphics g)``` and ```update(Graphics g)``` method to do nothing, solved the problem on linux. [Here is a code example of that](https://gist.github.com/hageldave/f22d6c3ef5120a7c711553426c72abcd) (repaint on component resized). On Windows however this did not solve the problem. I got a little suspicious there and found out that on windows there was another class calling the ```clearRect(...)``` method on the Canvas' Graphics object. So what I'm doing now is, using a delegate Graphics class that ignores calls to ```clearRect``` and return this in the Canvas' ```getGraphics``` method.
[Here's the code](https://github.com/hageldave/JPlotter/blob/b46fdc2d50e933543838c19626136bc14dd8eeac/jplotter/src/main/java/hageldave/jplotter/FBOCanvas.java) I'm resorting to right now (last method in that class is ```getGraphics()``` ).

I thought people may have the same problem , so I share my solution and maybe you guys like it enough to put some of it into lwjgl3-awt.

**Comment by hageldave** [comment]
To be precise, ```sun.awt.RepaintArea.paint(RepaintArea.java:235)``` calls ```clearRect(...)```.

**Comment by httpdigest** [comment]
Awesome, thanks for your work on this! I'd be really happy if you could pack this in a PR that we can discuss about.
