### ISSUE TITLE
Shared GL Context between AWTGLCanvas possible?

### ISSUE THREAD

**Issue by hageldave** [LWJGLX/lwjgl3-awt#16]
Hi,
Currently every `AWTGLCanvas` instances have their own GL context.
Because of this, I cannot share GL objects between them, e.g. I have to create the same texture for every Canvas separately, and more importantly keep track of the objects membership to the corresponding canvas and also delete them when destroying the respective canvas (even though I'm not sure whether the GL objects are deleted upon context destruction).

Is it possible that every `AWTGLCanvas` uses the same GL context so that objects can be shared easily between them?
What are the benefits of having separate contexts?

**Comment by hageldave** [comment]
Ah of course the befit is being able to have different frame buffer configurations for each.
In my case this is unimportant as I'm using FBOs as render targets, but I see that this feature cannot be compromised just like that.

Maybe there could be shared context versions of the `PlatformGLCanvas` implementations where the first instance creates a static shared context?

Or maybe have an `AWTGLCanvas` constructor that has `AWTGLCanvas` as argument which would result in the canvases to share their context?

**Comment by httpdigest** [comment]
Just set [GLData.shareContext](https://github.com/LWJGLX/lwjgl3-awt/blob/master/src/org/lwjgl/opengl/awt/GLData.java#L73) when creating a new AWTGLCanvas. The new canvas will then build a WGL/GLX share group with the given context.

**Comment by hageldave** [comment]
nice!!

**Comment by hageldave** [comment]
I see that this feature is currently windows exclusive as the `attribs.shareContext` field is nowhere used in `PlatformLinuxGLCanvas`.
Alright lets see what we can do about it...

**Comment by hageldave** [comment]
Are you planning on supporting this on Linux as well?

**Comment by hageldave** [comment]
Done as of #17
