### ISSUE TITLE
Share lists arguments are wrong way round

### ISSUE THREAD

**Issue by hageldave** [LWJGLX/lwjgl3-awt#18]
https://github.com/LWJGLX/lwjgl3-awt/blob/45a85af013c6cb742334295f0dd4e935db9c1849/src/org/lwjgl/opengl/awt/PlatformWin32GLCanvas.java#L337

The arguments in this method call have to be swapped since the second argument has to be a context that has no displaylist entries yet (see docs: https://javadoc.lwjgl.org/org/lwjgl/opengl/WGL.html#wglShareLists(long,long) ).

Due to this bug, it is impossible to share context among 3 or more canvases.

**Comment by hageldave** [comment]
Example:
Canvas A wants to share its context with canvas B and C. 

Creating Canvas B with A as share context succeeds.
Creating Canvas C with A as share context fails because A now already contains a display list.

**Comment by httpdigest** [comment]
Thanks for reporting! Would you like to do a PR to fix this?
