### ISSUE TITLE
No context available in initGL/paintGL

### ISSUE THREAD

**Issue by flowtsohg** [LWJGLX/lwjgl3-awt#24]
I copied the given single threaded example, but the GL context isn't available.

`effective` gives me an OpenGL 4.6 with null profile without further setup, I don't know if that's the actual version of the context that was supposedly created, or just my computer's capabilities.

Either way, any call to GL is a fatal error.

`swapBuffers()` is working in that it clears the canvas to black.

In addition, although probably not related, I tried spawning a GL 2 context without success, is there no access to versions below 3?

My code is running on Windows 10 64bits with Java 14, in case it matters.

**Comment by httpdigest** [comment]
Please provide a minimal reproducible example to reproduce the error and actual references/links to what you are referring to. What is the "given single threaded example"?

**Comment by flowtsohg** [comment]
The code that I have is the same as the one at https://github.com/LWJGLX/lwjgl3-awt/blob/master/test/org/lwjgl/opengl/awt/AWTTest.java except for `createCapabilities` which doesn't seem to exist.

**Comment by httpdigest** [comment]
Obviously, if you edited/removed any code from that example, the whole thing will not work anymore, especially with the very important call to `org.lwjgl.opengl.GL.createCapabilities()`, which tells LWJGL to initialize OpenGL function pointers.
The call is static imported from LWJGL 3 via `import static org.lwjgl.opengl.GL.*;`

**Comment by flowtsohg** [comment]
Oh boy now I feel silly, for some reason I assumed that was some old canvas related thing of Java. Thanks!

**Comment by httpdigest** [comment]
I mean... you do have LWJGL **3** in the classpath, do you? In that case, copy&pasting that very example verbatim will compiled just fine. And without LWJGL **3** nothing in lwjgl3-awt will work. :)

**Comment by flowtsohg** [comment]
My environment isn't the best. I am not a Java programmer, so I don't quite understand how things are set, plus I use VS Code and not a Java oriented IDE (it has a Java plugin, but it's not the best).

It works nicely with the given example, now gotta figure how to actually inject it into the project I am helping with. It's giving me issues because it's not in a JFrame, but rather in a JPanel which is itself nested a couple of levels, but I'll try to figure it out :)
