### ISSUE TITLE
How To Use

### ISSUE THREAD

**Issue by SimonMaracine** [LWJGLX/lwjgl3-awt#36]
There are instructions on how to use the code, but not how to actually use this library. There are no jars or anything.

I'm not new to programming, but I'm very new to Java and I don't know how to integrate third party code into my IntelliJ IDEA project, besides jars.

So, how do I use this thing?

**Comment by yuripourre** [comment]
In IntelliJ you can create a new Maven project. The new project will have a file named pom.xml where you can include dependencies from Maven central. I think that's the easiest way to manage dependencies.

Good resource: https://m.youtube.com/watch?v=pt3uB0sd5kY
