### ISSUE TITLE
Crash if trying to set GL version and profile

### ISSUE THREAD

**Issue by elect86** [LWJGLX/lwjgl3-awt#4]
Hi,

so, I'm playing with the sample and I noticed that if I also set the GL version and profile

        data.majorVersion = 3;
        data.minorVersion = 2;
        data.profile = GLData.Profile.CORE;

before adding the whole `GLData` to `JFrame`, then I'll get a crash at `glBegin` in `paintGL`

The crash may suggest a missing called to `createCapabilities();`, but this is not the case, I double checked

I also double checked the wgl context id received in case I set them or not, the id is always the same.

Also, making it current returns `true`, so it's definitely a valid context and it can be successfully made current

Moreover, all the data I set, they are successfully returned in `GLData effective`

Where is the error, then? I have no idea..

**Comment by httpdigest** [comment]
This is not a AWT/Swing issue. There is no glBegin() in a 3.2 Core Context. You will get the same behaviour in LWJGL3 with using GLFW.

**Comment by httpdigest** [comment]
I highly suggest you use the new GLXXC classes in LWJGL3. For example org.lwjgl.opengl.GL32C. This class will have only the methods that you can use in that core context.

**Comment by elect86** [comment]
Oh you right, I totally missed that, Compatible profile does run flawless indeed

Sorry
