### ISSUE TITLE
Providing binary releases

### ISSUE THREAD

**Issue by dolda2000** [LWJGLX/lwjgl3-awt#46]
In short, since you need a Mac to build the MacOS native library, it would be nice if the project could offer binary releases for those of us who don't have Macs but yet want to support Mac users.

**Comment by SWinxy** [comment]
The mac dylib is packaged in the jar. Wdym?

**Comment by httpdigest** [comment]
The LWJGLX/lwjgl3-awt library is published after each build on the Maven/Gradle repository oss.sonatype.org as a Maven artefact. You can use that in any Maven/Gradle project (just look at the pom.xml).
If you are not using Maven/Gradle or Ivy for dependency management (you should) then you can download the jar directly from https://oss.sonatype.org/content/repositories/snapshots/org/lwjglx/lwjgl3-awt/0.1.9-SNAPSHOT/ (use the file with the highest build number).

**Comment by httpdigest** [comment]
@dolda2000 looking at your projects, in particular https://github.com/dolda2000/hafen-client , it seems you use Ant for most/all your projects. In that case you can use [Apache Ivy](https://ant.apache.org/ivy/) for automatic dependency management/download in your Ant build script. You then also don't need to checkin library dependencies anymore in your Git repo.

**Comment by dolda2000** [comment]
Sorry, as someone who hasn't used Maven, I didn't realize that it doubled as a download central of sorts. Might I suggest putting a release here on Github just to reduce confusion for others in the same position?

**Comment by SWinxy** [comment]
Maven and Gradle make your life easier, but it may be useful to publish GitHub releases. Afaik the dylib is manually built, and that should be automated with GH actions.

**Comment by SWinxy** [comment]
Closed because #57 is merged, which means that the native library is no longer.
