### ISSUE TITLE
AWTGLCanvas displays blank screen in fullscreen mode on MacOS BigSur

### ISSUE THREAD

**Issue by DrunkyBard** [LWJGLX/lwjgl3-awt#49]
Steps to reproduce:

1) Launch AWTTest application on macOS
2) Press on fullscreen button
3) Canvas displays blank white window

I reproduced given issue on macOS 11.3.1

**Comment by bumfo** [comment]
I'm having the same issue. Looks like setting context = 0 (so that everything is recreated) can resolve the issue. But that should be a long term solution...
