### ISSUE TITLE
Consolidate main / master branches

### ISSUE THREAD

**Issue by OndrejSpanel** [LWJGLX/lwjgl3-awt#52]
Two branches start to exist after 05784f9517ac3fa6ce30fa17a2b61c5c2d10ee3e - main and master. It seem main is used now to build the artifacts automatically, but master contains several commits with various fixes by @Spasi. This is probably unintended and master should be merged into main and deleted?

**Comment by SWinxy** [comment]
Deleted master branch. Main has been the branch to work on for some time.
