### ISSUE TITLE
Prerelease artifact?

### ISSUE THREAD

**Issue by skalarproduktraum** [LWJGLX/lwjgl3-awt#7]
Hi @httpdigest,

I was wondering whether it'd be possible to have a non-snapshot version published soon(ish), just for reproducible builds? Would be great!

Thanks!

**Comment by httpdigest** [comment]
Sure, will do a complete CI pipeline with Travis (for automatically publishing snapshot as well as release versions), as I've already done this for JOML. Probably this weekend.

**Comment by skalarproduktraum** [comment]
Perfect, thank you very much!

**Comment by httpdigest** [comment]
Hey, didn't have time this we, but it's going to happen by next we - I promise. :)

**Comment by httpdigest** [comment]
@skalarproduktraum Travis build and automatic deploy on push to oss.sonatype.org (for snapshots versions) and to maven central (for non-snapshot versions) has been added. However, I do not think that we should have a first release version yet. I'd like to do that as soon as we have a working Mac OS implementation. For snapshot versions you should be fine using the `https://oss.sonatype.org/content/repositories/snapshots/` repo.

**Comment by skalarproduktraum** [comment]
@httpdigest, thanks for the work! I do however differ on the release issue -- it'd be very important to me to have a non-snapshot build, for two reasons:

* I would actually like to merge my feature branch in github.com/scenerygraphics/scenery and githublcom/scenerygraphics/sciview into the master branch and do (another) preview release myself. These projects are part of the ImageJ ecosystem for scientific image analysis and visualisation, and from ImageJ we inherited the rule to not want SNAPSHOT dependencies on master for the sake of reproducible builds -- as SNAPSHOTs are always a bit of a surprise bag :smile: 
* while I do understand you want the have macOS support first, but from my experience on that platform, that'll take a bit and be quite painful. 

That being said, I'd be super-grateful for something like 0.1 :+1:
