### ISSUE TITLE
Your GPG key expired, so you cannot deploy

### ISSUE THREAD

**Issue by hageldave** [LWJGLX/lwjgl3-awt#70]
I just checked your github actions, and you have a 'build-and-publish' workflow, that is failing. 
https://github.com/LWJGLX/lwjgl3-awt/actions/runs/7365969382
I checked the output of the build, and it turns out that the gpg signing plugin errors, which is due to [missing a signing key](https://github.com/LWJGLX/lwjgl3-awt/actions/runs/7365969382/job/20047775230#step:5:501).
However, in the very beginning of the build, a [gpg key is imported](https://github.com/LWJGLX/lwjgl3-awt/actions/runs/7365969382/job/20047775230#step:5:20). So I went and [looked up the key](http://keyserver.ubuntu.com/pks/lookup?search=6D4BA690F3FCD58E&fingerprint=on&op=index), and it turns out that it expired on 2022-10-24.

This is why your build is not deploying to maven. @httpdigest You can simply renew your key and it should be solved. I found these instructions on how to do it:
https://superuser.com/questions/813421/can-you-extend-the-expiration-date-of-an-already-expired-gpg-key
Or you can create a new key and replace the old one.

**Comment by SWinxy** [comment]
The workflow is now working again; see #73.
