### ISSUE TITLE
Possible to render on an existing AWT thread?

### ISSUE THREAD

**Issue by Jire** [LWJGLX/lwjgl3-awt#8]
My AWT applet has built-in code to render with GL. I need to be able to create the GL context on the same thread as the AWT applet. Is this possible?

**Comment by httpdigest** [comment]
See this test. It already does this in the AWT thread: https://github.com/LWJGLX/lwjgl3-awt/blob/master/test/org/lwjgl/opengl/awt/AWTTest.java#L57
